config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :jobs do
    collection do
      get "mine"
    end
  end
  resources :claims

  root "application#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :user
  belongs_to :job

  enum status: [:created, :done]
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_one :claim

  geocoded_by :pick_up_address, latitude: :pick_up_latitude, longitude: :pick_up_longitude

  validates_presence_of :title, :description, :pick_up_address, :drop_off_address, :pick_up_latitude, :pick_up_longitude, :drop_off_latitude,
                        :drop_off_longitude
end

app/models/user.rb
class User < ApplicationRecord
  has_many :jobs
  has_many :claims
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  include ExceptionHandler

  def home; end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def after_sign_in_path_for(_resource)
    jobs_path
  end
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  def index
    @claims = current_user.claims.joins(:job)
  end

  def create
    @job = Job.find(claim_params[:job_id])
    if @job.user_id != current_user.id
      @claim = current_user.claims.create!(claim_params)

      redirect_to jobs_path
    else
      flash[:danger] = "Cannot claim your own job!"

      redirect_to @job
    end
  end

  private

  def claim_params
    params.permit(:job_id)
  end
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |_e|
      render file: "public/404.html", status: :not_found
    end

    # rescue_from ActiveRecord::RecordInvalid do |_e|
    #   render file: "public/422.html", status: :unprocessable_entity
    # end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job, only: [:destroy]

  def index
    lat = params[:lat] || "3.1466"
    lng = params[:lng] || "101.6958"
    @jobs = Job.joins(:user).near("#{lat},#{lng}", 60).order(:distance)
  end

  def mine
    @job = current_user.jobs
  end

  def new
    @job = Job.new
  end

  def show
    @job = Job.left_outer_joins(:claim).select("jobs.*, (claims.job_id IS NOT NULL) AS claimed").find(params[:id])
  end

  def create
    @job = current_user.jobs.create(job_params)

    if @job.valid?
      redirect_to jobs_path
    else
      flash[:danger] = @job.errors.full_messages.join("\n")

      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @job = current_user.jobs.find(params[:id])

    if @job.claim.nil?
      @job.destroy

      redirect_to jobs_path
    else
      flash[:danger] = "This job is claimed"

      render :show, status: :method_not_allowed
    end
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :description, :pick_up_address, :drop_off_address, :pick_up_latitude, :pick_up_longitude, :drop_off_latitude,
                                :drop_off_longitude)
  end
end

app/helpers/api/registrations_helper.rb
module Api::RegistrationsHelper
end

app/helpers/api/sessions_helper.rb
module Api::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claim_helper.rb
module ClaimHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/views/application/home.html.erb
<% content_for :navbar do %>
  <li class="nav-item">
    <%= link_to "Log In", new_user_session_path, class: "m-3" %>
  </li>
  <li class="nav-item">
    <%= link_to "Sign Up", new_user_registration_path  %>
  </li>
<% end %>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Work better with us</h1>
    <p class="lead py-3">GoGet is a community platform for reliable and skilled part time help. Empower the community to achieve greater productivity and connectivity in everyday work.</p>
    <%= link_to "Create job", new_job_path, class: "button btn btn-outline-success" %>
  </div>
</div>

app/views/claim/show.html.erb
<h1>Claim#show</h1>
<p>Find me in app/views/claim/show.html.erb</p>

app/views/claims/index.html.erb
<h1>Your claimed job</h1>
<table class="table table-striped", style="width: 100%">
  <colgroup>
    <col span="1" style="width: 50%;">
    <col span="1" style="width: 25%;">
    <col span="1" style="width: 25%;">
  </colgroup>
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Pick up address</th>
      <th scope="col">Drop off address</th>
    </tr>
  </thead>
  <tbody>
    <% @claims.each do |claim| %>
      <tr>
        <td colspan="1">
          <%= link_to claim.job.title, claim.job %>
        </td>
        <td>
          <%= link_to claim.job.pick_up_address, "https://www.google.com/maps/search/?api=1&query=#{claim.job.pick_up_latitude},#{claim.job.pick_up_longitude}", target: "_blank" %>
        </td>
        <td>
          <%= link_to claim.job.drop_off_address, "https://www.google.com/maps/search/?api=1&query=#{claim.job.drop_off_latitude},#{claim.job.drop_off_longitude}", target: "_blank" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/job/index.html.erb
<h1>Work better with us</h1>
	<%= link_to new_user_session_path do %>Sign In<% end %>
    # <%= link_to new_user_registration_path do %>Sign Up<% end %>
<p>Find me in app/views/job/index.html.erb</p>

app/views/jobs/index.html.erb
<% content_for :navbar do %>
  <li class="nav-item">
    <%= link_to "Your Jobs", mine_jobs_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "View Claimed Jobs", claims_path, class: "nav-link" %>
  </li>
  <%= link_to "Create job", new_job_path, class: "button m-3 btn btn-outline-success", class: "btn btn-outline-success my-2 my-sm-0" %>
  <li class="nav-item">
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
  </li>
<% end %>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Work better with us</h1>
    <p class="lead py-3">GoGet is a community platform for reliable and skilled part time help. Empower the community to achieve greater productivity and connectivity in everyday work.</p>
    <%= link_to "Create job", new_job_path, class: "button btn btn-success" %>
  </div>
</div>
<h2>Job List</h2>
<% @jobs.each do |job| %>
  <div class="job-title-group">
    <small>Created by: <%= job.user.username %></small>
    <div class="job-title">
      <%= link_to job.title, job_path(job) %>
    </div>
  </div>
<% end %>
<script>
  function getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition((position) => {
        window.location.replace(`${window.location}?lat=${position.coords.latitude}&lng=${position.coords.longitude}`);
      });
    } else {
      x.innerHTML = "Geolocation is not supported by this browser.";
    }
  }
  
  (() => {
    let searchParams = new URLSearchParams(window.location.search);
  
    if (!(searchParams.has("lat") && searchParams.has("lng"))) {
      getLocation()
    }
  })()
</script>

app/views/jobs/mine.html.erb
<h1>Your job</h1>
<table class="table table-striped", style="width: 100%">
  <colgroup>
    <col span="1" style="width: 50%;">
    <col span="1" style="width: 25%;">
    <col span="1" style="width: 25%;">
  </colgroup>
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Pick up address</th>
      <th scope="col">Drop off address</th>
    </tr>
  </thead>
  <tbody>
    <% @job.each do |job| %>
      <tr>
        <td>
          <%= link_to job.title, job %>
        </td>
        <td>
          <%= link_to job.pick_up_address, "https://www.google.com/maps/search/?api=1&query=#{job.pick_up_latitude},#{job.pick_up_longitude}", target: "_blank" %>
        </td>
        <td>
          <%= link_to job.drop_off_address, "https://www.google.com/maps/search/?api=1&query=#{job.drop_off_latitude},#{job.drop_off_longitude}", target: "_blank" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<h2>Please write down your job details</h2>
<%= form_with model: @job do |f| %>
  <div class="field form-group">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: "Enter title", class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: "Enter your description", class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :pick_up_address %>
    <%= f.text_field :pick_up_address, placeholder: "Enter your pick up address", class: "form-control", id: "pick-up-address" %>
  </div>
  <div class="field form-group">
    <%= f.label :pick_up_latitude %>
    <%= f.text_field :pick_up_latitude, placeholder: "Enter your pick up latitude", class: "form-control", id: "pick-up-lat" %>
  </div>
  <div class="field form-group">
    <%= f.label :pick_up_longitude %>
    <%= f.text_field :pick_up_longitude, placeholder: "Enter your pick up longitude", class: "form-control", id: "pick-up-lng" %>
  </div>
  <div class="field form-group">
    <%= f.label :drop_off_address %>
    <%= f.text_field :drop_off_address, placeholder: "Enter your drop off address", class: "form-control", id: "drop-off-address" %>
  </div>
  <div class="field form-group">
    <%= f.label :drop_off_latitude %>
    <%= f.text_field :drop_off_latitude, placeholder: "Enter your drop off latitude", class: "form-control", id: "drop-off-lat" %>
  </div>
  <div class="field form-group">
    <%= f.label :drop_off_longitude %>
    <%= f.text_field :drop_off_longitude, placeholder: "Enter your drop off longitude", class: "form-control", id: "drop-off-lng" %>
  </div>
  <%= f.submit "Create", class: "btn btn-outline-success" %>
<% end %>
<script>
  function setupAutocomplete(id, callback) {
    const input = document.getElementById(id);
    const options = {
      componentRestrictions: { country: "my" },
      fields: ["geometry"],
      strictBounds: false,
    };
    const autocomplete = new google.maps.places.Autocomplete(input, options);
  
    autocomplete.addListener("place_changed", () => {
      const place = autocomplete.getPlace();
      console.log(place.geometry.location)
      callback(place.geometry.location.lat(), place.geometry.location.lng());
    });
  }
  
  function initializeAutocomplete(params) {
    setupAutocomplete("pick-up-address", (lat, lng) => {
      document.getElementById("pick-up-lat").value = lat;
      document.getElementById("pick-up-lng").value = lng;
    });
  
    setupAutocomplete("drop-off-address", (lat, lng) => {
      document.getElementById("drop-off-lat").value = lat;
      document.getElementById("drop-off-lng").value = lng;
    });
  }
</script>

app/views/jobs/show.html.erb
<div class="job-content">
  <h1><%= @job.title %></h1>
  <div class="job-content-body">
    <div class="job-content-description">
      <span class="job-content-title">
        About this job
      </span>
      <p><%= @job.description %></p>
    </div>
    <span class="job-content-subtitle">
      Pick up address
    </span>
    <p>
      <%= link_to @job.pick_up_address, "https://www.google.com/maps/search/?api=1&query=#{@job.pick_up_latitude},#{@job.pick_up_longitude}", target: "_blank" %>
    </p>
    <span class="job-content-subtitle">
      Drop off address 
    </span>
    <p>
      <%= link_to @job.drop_off_address, "https://www.google.com/maps/search/?api=1&query=#{@job.drop_off_latitude},#{@job.drop_off_longitude}", target: "_blank" %>
    </p>
  </div>
  <% if @job.user_id == current_user.id %>
    <%= button_to "Delete", {controller: "jobs", action: "destroy", user_id: session[:user_id]} , method: :delete, class: "btn btn-danger" %>
  <% else %>
    <% if !@job.claimed %>
      <%= button_to 'Claim job', {controller: "claims", action: "create", job_id: @job.id, user_id: session[:user_id]} , method: :post, class: "btn btn-success" %>
    <% else %>
      <% if @job.claim.user_id == current_user.id %>
        <button class="btn btn-dark disabled">Claimed by you</button>
      <% else %>
        <button class="btn btn-dark disabled">Claimed by someone else</button>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdJob</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script async
    src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google_map_api_key %>&libraries=places&callback=initializeAutocomplete"></script>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <% if current_user %>
          <%= link_to 'OdJob', jobs_path, class: "navbar-brand" %>
        <% else %>
          <%= link_to 'OdJob', root_path, class: "navbar-brand" %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto"></ul>
          <ul class="navbar-nav">
            <%= yield :navbar %>
          </ul>
        </div>
      </nav>
      <% flash.each do |type, msg| %>
        <div class="alert alert-<%= type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>